name: Release
on:
  push:
    tags:
      - '*'

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      pnpm_store_path: ${{ steps.pnpm.outputs.pnpm_store_path }}
      pnpm_hash_key: ${{ steps.pnpm.outputs.pnpm_hash_key }}
      pnpm_restore_key: ${{ steps.pnpm.outputs.pnpm_restore_key }}
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - name: pnpm env
        id: pnpm
        shell: bash
        run: |
          echo "pnpm_store_path=$(devbox run pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          echo "pnpm_hash_key=${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}" >> "$GITHUB_OUTPUT"
          echo "pnpm_restore_key=${{ runner.os }}-pnpm-store-" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm.outputs.pnpm_store_path }}
          key: ${{ steps.pnpm.outputs.pnpm_hash_key }}
          restore-keys: ${{ steps.pnpm.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --frozen-lockfile

  apps_player:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/player
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/player
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_components:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/components
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/components
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


  packages_player-actions:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/player-actions
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/player-actions
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_player-state:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/player-state
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/player-state
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_player-config:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/player-config
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/player-config
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  packages_utils:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/utils
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/utils
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_clients:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/clients
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/clients
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_button-actions:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/button-actions
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/button-actions
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  packages_media-backend:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: true
      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ needs.bootstrap.outputs.pnpm_store_path }}
          key: ${{ needs.bootstrap.outputs.pnpm_hash_key }}
          restore-keys: ${{ needs.bootstrap.outputs.pnpm_restore_key }}
      - name: install
        run: devbox run pnpm install --offline
      - name: build
        run: devbox run pnpm run build --scope @podlove/media-backend
      - name: publish
        run: devbox run pnpm publish --no-git-checks --access public --filter @podlove/media-backend
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
